---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hytale
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: hytale
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      hytale:
        annotations:
          reloader.stakater.com/auto: "true"
          type: statefulset
          replicas: 1
          strategy: RollingUpdate
        containers:
          hytale:
            stdin: true
            tty: true
            image:
              repository: deinfreu/hytale-server
              tag: experimental-0.1.3
            ports:
              - containerPort: &udpPort 5520
                protocol: UDP
            env:
              SERVER_IP: "0.0.0.0"
              SERVER_PORT: *udpPort
              PROD: "FALSE"
              DEBUG: "FALSE"
              TZ: "America/Los_Angeles"
              HYTALE_ACCEPT_EARLY_PLUGINS: "TRUE"
              HYTALE_AUTH_MODE: "TRUE"
              JAVA_ARGS: >-
                -Xms8G -Xmx8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200
                -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20
                -XX:InitiatingHeapOccupancyPercent=15 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem
                -XX:MaxTenuringThreshold=1 -XX:+UseCompactObjectHeaders -Djava.net.preferIPv4Stack=true
                -Dfile.encoding=UTF-8
            securityContext:
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 2
                memory: 8Gi
              limits:
                memory: 12Gi
    service:
      hytale:
        controller: hytale
        type: LoadBalancer
        annotations:
          mc-router.itzg.me/externalServerName: "hytale.ok8.sh"
        ports:
          game:
           protocol: UDP
           port: *udpPort
    persistence:
      bans-json:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        advancedMounts:
          hytale:
            app:
              - path: /home/container/bans.json
                subPath: bans.json
                readOnly: true
      machine-id:
        type: configMap
        name: "{{ .Release.Name }}-configmap"
        advancedMounts:
          hytale:
            app:
              - path: /etc/machine-id
                subPath: machine-id
                readOnly: true
      data:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /home/container