---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./dnsendpoint.yaml
  - ./ocirepository.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: hytale-configmap
    files:
      - ./resources/bans.json
      - ./resources/machine-id
generatorOptions:
  disableNameSuffixHash: true