---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  interval: 30m
  values:
    fullnameOverride: renovate-operator
    route:
      enabled: true
      hostnames: ["renovate.ok8.sh"]
      parentRefs:
        - name: internal
          namespace: networking
          sectionName: https
    webhook:
      enabled: true