---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coturn
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: coturn
  values:
    controllers:
      coturn:
        replicas: 1
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/coturn/coturn
              tag: 4.8.0@sha256:5de3fc6be2da60c3d93f40aa57e0f43188d9183c0053b25581883f5ccd252bdb
            args:
              - -c
              - /config/turnserver.conf
            securityContext:
              capabilities:
                add:
                  - NET_BIND_SERVICE

    service:
      app:
        controller: coturn
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          lbipam.cilium.io/ips: 10.0.20.62
          external-dns.alpha.kubernetes.io/hostname: turn.ok8.sh
        ports:
          turn-udp:
            port: 3478
            targetPort: 3478
            protocol: UDP
          turn-udp-alt:
            port: 3479
            targetPort: 3479
            protocol: UDP
          turn-tcp:
            port: 3478
            targetPort: 3478
            protocol: TCP
          turn-tcp-alt:
            port: 3479
            targetPort: 3479
            protocol: TCP
          turn-tls:
            port: 5349
            targetPort: 5349
            protocol: TCP

    persistence:
      config:
        type: secret
        name: coturn-secret
        globalMounts:
          - path: /config/turnserver.conf
            subPath: turnserver.conf
            readOnly: true
      tls:
        type: secret
        name: ok8-sh-tls
        globalMounts:
          - path: /tls
            readOnly: true