---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/namespace
replacements:
  - path: ../../components/replacements/ks.yaml
resources:
  #- ./acars/ks.yaml
  - ./bitfocus/ks.yaml
  - ./glance/ks.yaml
  - ./govee2mqtt/ks.yaml
  - ./home-assistant/ks.yaml
  - ./immich/ks.yaml
  - ./mosquitto/ks.yaml
  - ./music-assistant/ks.yaml
  - ./ok8-sh/ks.yaml
  #- ./opencloud/ks.yaml
  - ./openspeedtest/ks.yaml
  - ./renovate/ks.yaml
  #- ./rtlamr2mqtt/ks.yaml
  - ./zigbee2mqtt/ks.yaml
