---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waifulabs
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: waifulabs-arm64
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: waifulabs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: waifulabs
    namespace: actions-runner-system
  - kind: ServiceAccount
    name: waifulabs-arm64
    namespace: actions-runner-system
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: waifulabs
spec:
  roles: ["os:admin"]
