---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: default-pg-credentials
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: default-app
  data:
    - match:
        secretKey: &key dbname
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key fqdn-jdbc-uri
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key fqdn-uri
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key host
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key jdbc-uri
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key password
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key pgpass
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key port
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key uri
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key user
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key
    - match:
        secretKey: &key username
        remoteRef:
          remoteKey: default-pg-credentials
          property: *key

