---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: default-pg-credentials
spec:
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: default-app
  data:
    - match:
        remoteRef:
          remoteKey: default-pg-credentials