---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kashalls-app-private-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kashalls-app-private-key
    template:
      data:
        # github_token: "{{ .RUNNER_TOKEN }}"
        github_app_id: "{{ .APP_ID }}"
        github_app_installation_id: "{{ .INSTALLATION_ID }}"
        github_app_private_key: "{{ .PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: github

---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: renovate-kashalls-github-token
spec:
  appID: "356911"
  installID: "111237872"
  auth:
    privateKey:
      secretRef:
        name: kashalls-app-private-key
        key: github_app_private_key
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-kashalls-github-token
spec:
  refreshInterval: "30m0s"
  target:
    name: renovate-kashalls-github-token
    template:
      type: Opaque
      engineVersion: v2
      data:
        GITHUB_COM_USER: d2FpZnVsYWJzCg==
        GITHUB_COM_TOKEN: "{{ .token }}"
        RENOVATE_TOKEN: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: renovate-kashalls-github-token
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: kashalls
spec:
  discoveryFilter: kashalls/*
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: '["pnpm run bundle"]'
    - name: RENOVATE_ENDPOINT
      value: https://api.github.com/
    - name: RENOVATE_PLATFORM
      value: github
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  image: ghcr.io/renovatebot/renovate:43.39.2
  parallelism: 5
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-kashalls-github-token
  webhook:
    enabled: true
    authentication:
      enabled: false