---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-pg-credentials
spec:
  deletionPolicy: Delete
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: immich-app
  data:
    - match:
        remoteRef:
          remoteKey: immich-pg-credentials