---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-pg-credentials
spec:
  deletionPolicy: Delete
  refreshInterval: 1h0m0s
  secretStoreRefs:
    - name: onepassword
      kind: ClusterSecretStore
  selector:
    secret:
      name: immich-app
  data:
    - match:
        secretKey: &key dbname
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key fqdn-jdbc-uri
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key fqdn-uri
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key host
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key jdbc-uri
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key password
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key pgpass
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key port
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key uri
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key user
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key
    - match:
        secretKey: &key username
        remoteRef:
          remoteKey: immich-pg-credentials
          property: *key