---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bitfocus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: bitfocus
  values:
    controllers:
      bitfocus:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/bitfocus/companion/companion
              tag: v4.1.4@sha256:cd6ea58c303c2d613605e6634d49b45586b3780cb4f6f50f2c2a766d96c500c5
            env:
              TZ: America/Los_Angeles
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            #resources:
            #  requests:
            #    cpu: 100m
            #    memory: 64Mi
            #  limits:
            #    memory: 96Mi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: bitfocus
        type: LoadBalancer
        ports:
          http:
            port: 8000
          satelite-api:
            port: 16622
          satelite-api2:
            port: 16623
          websocket:
            port: 28492
    route:
      app:
        hostnames: ["{{ .Release.Name }}.ok8.sh", "companion.ok8.sh"]
        parentRefs:
          - name: internal
            namespace: networking
            sectionName: https
    persistence:
      companion:
        existingClaim: bitfocus