---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hookshot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: hookshot-secret
    template:
      engineVersion: v2
      data:
        GITHUB_KEY: >-
          {{ .GITHUB_PRIVATE_KEY }}
        PASSKEY: "{{ .hookshot_passkey | b64dec }}"
      templateFrom:
        - target: Data
          configMap:
            name: hookshot-config
            items:
              - key: config.yaml
                templateAs: Values
        - target: Data
          configMap:
            name: hookshot-config
            items:
              - key: registration.yaml
                templateAs: Values
  dataFrom:
    - extract:
        key: hookshot
      rewrite:
        - regexp:
            source: "(.*)"
            target: "hookshot_$1"
    - extract:
        key: github
      rewrite:
        - regexp:
            source: "(.*)"
            target: "GITHUB_$1"
